name: linux

on: 
	push:
		paths:
			- 'linux'

jobs:
	build:
		runs-on: ubuntu-20.04

		steps:
		   -uses: actions/checkout@v2
		   
                   -name: Download and unzip current commit number of submodule
		    run: currentCommitNum=$(git ls-files -s linux | awk '{print $2}'
		    run: wget https://github.com/ycho98/linux/archive/$currentCommitNum.zip
		    run: unzip $currentCommitNum.zip
                    run: ./build-linux.sh linux-$currentCommitNum tinyconfig

